import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro', // Introduction / Preface
    {
      type: 'category',
      label: 'Module 1: ROS 2 Foundation',
      collapsible: true,
      collapsed: false,
      items: [
        'module-1-ros2/intro',
        'module-1-ros2/ros2-architecture',
        'module-1-ros2/packages-and-build-system',
        'module-1-ros2/nodes-topics-services-actions',
        'module-1-ros2/launch-files',
        'module-1-ros2/urdf-robot-description',
      ],
    },
    {
      type: 'category',
      label: 'Module 2: Digital Twins',
      collapsible: true,
      collapsed: true,
      items: [
        'module-2-digital-twin/gazebo-physics-simulation',
        'module-2-digital-twin/sensor-simulation-lidar-realsense',
        'module-2-digital-twin/unity-visualization',
      ],
    },
    {
      type: 'category',
      label: 'Module 3: NVIDIA Isaac Sim',
      collapsible: true,
      collapsed: true,
      items: [
        {
          type: 'autogenerated', // Use autogen for this folder
          dirName: 'module-3-nvidia-isaac', 
        },
      ],
    },
    // Add additional modules here
  ],
};

export default sidebars;