import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI Course',
      items: [
        'introduction', // The main course introduction
        {
          type: 'category',
          label: 'Module 1: ROS 2 Core Fundamentals',
          link: {
            type: 'doc',
            id: 'ros-2-basics-intro',
          },
          items: [
            // Future sub-pages for this module can go here
          ],
        },
        {
          type: 'doc',
          id: 'vla_module', // Direct link to the VLA module page
          label: 'Module 2: Vision-Language-Action (VLA) Pipeline',
        },
        {
          type: 'category',
          label: 'Module 3: Humanoid Kinematics and Control',
          link: {
            type: 'doc',
            id: 'humanoid-kinematics-intro',
          },
          items: [
            // Future sub-pages for this module can go here
          ],
        },
        {
          type: 'category',
          label: 'Module 4: Synthetic Data and Simulation',
          link: {
            type: 'doc',
            id: 'simulation-data-intro',
          },
          items: [
            // Future sub-pages for this module can go here
          ],
        },
      ],
    },
  ],
};

export default sidebars;