import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Physical AI Course',
      items: [
        'introduction',
        'vla_module',
        {
          type: 'category',
          label: 'Chapter 1: ROS 2 Basics',
          items: ['chapter1_sub_topic_a', 'chapter1_sub_topic_b'], // Dummy sub-topics
        },
        {
          type: 'category',
          label: 'Chapter 2: Digital Twin Module',
          items: ['chapter2_sub_topic_a'], // Dummy sub-topics
        },
        {
          type: 'category',
          label: 'Chapter 3: Humanoid Control',
          items: ['chapter3_sub_topic_a', 'chapter3_sub_topic_b', 'chapter3_sub_topic_c'], // Dummy sub-topics
        },
        {
          type: 'category',
          label: 'Appendix: Tools Setup',
          items: ['appendix_tool_a',. 'appendix_tool_b'], // Dummy sub-topics
        },
      ],
    },
  ],
};

export default sidebars;
